### ISSUE TITLE
As Of data doesn't work back in February

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/forecast-eval#188]
Selecting the As Of date to be mid February doesn't produce any data (all gray, no black).  Must be a bug?

![Screen Shot 2021-09-30 at 9 47 26 AM](https://user-images.githubusercontent.com/732541/135467604-cf50d1f4-f983-491b-8637-57c41add39ad.png)

**Comment by nmdefries** [comment]
"Totaled" truth data is missing for as-of dates prior to 02-19-2021 because the first data in covidcast for US territories (American Samoa, Guam, etc) was issued on 02-19-2021 (releasing data all the way back to Feb 2020). To produce as-of data for the "Totaled Over States" location, we sum truth data over all state-level regions that are forecast by selected forecasters. If any regions have missing values, the final summed truth value will also be missing.

The individual regions causing this problem, e.g. Guam, also don't have truth data for as-of dates prior to 02-19-2021, so any fix would need to deal with those as well.

How do you want to handle this? Some ideas:
* Drop territories from score calculation and truth data if the as-of date is before 02-19. (Doesn't generalize to individual regions.)
* Ignore (treat as 0) missing values when calculating the sum only if the as-of date is before 02-19.
* Ignore (treat as 0) missing values when calculating the sum generally.
* Add a message explaining why as-of data is missing for certain selections.

**Comment by krivard** [comment]
* generate and upload backissues for US territories

we have code that figures out the JHU-CSSE gitref for each day's issue, then can run the jhu indicator using that gitref instead of the most recent file. we'd just need code to either restrict the output to only territories, or drop the unnecessary lines after the fact. 

iirc there were a few format changes to JHU-CSSE data over the last year and a half that may have affected territory reporting in particular, so that may generate additional speed bumps.

**Comment by ryantibs** [comment]
Thanks for the explanation and discussion.  Katie's option is of course ideal.  Before deciding whether an intermediate solution (one of Nat's) is worth doing, can I get an estimate of how expensive Katie's option would be in terms of time?  Do we expect this to take many weeks?  A week?  Or a day?

**Comment by krivard** [comment]
A week if Andrew can do it, though there are some other (higher-priority?) things he's working on ([HHS hospital admissions for influenza](https://github.com/cmu-delphi/delphi-epidata/issues/720) & other columns added since the last schema update) and he's in midterms so it could be a while. 2-3 weeks if we put someone new on it. Maybe less if QX has bandwidth.
